# Generated by Django 5.0.3 on 2024-03-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='num_reviews',
            new_name='review_number',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number_of_beds',
            new_name='bed_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
    ]
