# Generated by Django 5.0.3 on 2024-03-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_rename_num_reviews_hotel_review_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_guests',
            new_name='guest_number',
        ),
    ]
