# Generated by Django 5.0.3 on 2024-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_num_guests_booking_guest_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
